# Generated by Django 5.1.4 on 2025-01-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('study_type', models.CharField(max_length=50)),
                ('hours_per_day', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('subject', models.CharField(max_length=255)),
                ('resources', models.TextField()),
                ('progress', models.IntegerField(default=0)),
            ],
        ),
    ]
